apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ecommerce
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: change_me_root
  MYSQL_DATABASE: docker_last_work
  MYSQL_USER: ecommerce
  MYSQL_PASSWORD: change_me_app
